export const actions = {
  GET_MOVIES: 'GET_MOVIES',
  LOADING_MOVIES: 'LOADING_MOVIES',
  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIES_ERROR: 'GET_MOVIES_ERROR',
  CLEAR_MOVIES: 'CLEAR_MOVIES',
};
